// react-front-end/src/components/welcome/welcome.js
import React from "react";


class Welcome extends React.Component {
    render() {
        return (
            <div>
                <h1 className={"text-center"}>Welcome </h1>
                <img src={"./assets/product.png"} className={" center-block"}/>
            </div>
        )}
}

export default Welcome;

// front-end/src/app/welcome/welcome.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
export class WelcomeComponent implements OnInit {

  productImage = 'assets/product.png';

  constructor() { }

  ngOnInit() {
  }

}

<div class="jumbotron">
  <h1 class="text-center">Welcome </h1>
  <img [src]="productImage" class="center-block">
</div>
